# permissions for end users to view keepalivedgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keepalivedgroup-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - keepalivedgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - keepalivedgroups/status
  verbs:
  - get
