# permissions for end users to edit keepalivedgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keepalivedgroup-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - keepalivedgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - keepalivedgroups/status
  verbs:
  - get
